ms_web/members/urls.py
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path('',views.register,name='register'),
    path('logout/',views.logoutUser,name='logout'),
    path('profile/<int:pk>',views.profile, name='profile'),
    path('profile/edit_profile',views.edit_profile,name='edit_profile'),
    path('profile/edit_profile/password_change',views.password_change,name='password_change')
]

ms_web/ms_web/urls.py
from django.contrib import admin
#from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls
from django.views.static import serve

urlpatterns = [
                  path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
                  path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
                  path('admin/', admin.site.urls),
                  path('', include('msagh_website.urls')),
                  path('members/', include('members.urls')),
                  path('', include("django.contrib.auth.urls")),
                  path('email/', include(email_urls)),  # verification user path
              # 	path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
#path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
              ]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # Operation for images in meme section


handler404 = 'ms_web.views.handle_not_found'

ms_web/msagh_website/urls.py
from django.urls import path
from. import views
from django.contrib.auth import views as auth_views #import this

app_name = "msagh_website"

urlpatterns = [
    path('',views.base,name='base'),
    path('spotted/<int:pk>', views.one_spot, name="one_spot"),
    path('spotted/', views.spotted, name='spotted'),
    path('new_spot', views.new_spot, name="new_spot"),
    # path('memes/', views.memes, name="memes"),
    # path('memes/<int:pk>', views.one_meme, name="one_meme"),
    # path('new_meme/',views.new_meme,name='new_meme'),
    path('contact/', views.contact, name="contact"),
    path("password_reset/", views.password_reset_request, name="password_reset"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    # URL connected with passsword
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),

]

ms_web/msagh_website/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxLengthValidator, MinLengthValidator
from msagh_website.validators import validate_size,validate_shape
User = settings.AUTH_USER_MODEL



# Create your models here.
class Spot(models.Model):
    title = models.CharField(validators=[MinLengthValidator(5)], max_length=70)
    pub_date = models.DateTimeField(auto_now_add=True)
    admin_aproved = models.BooleanField(default=False)
    user = models.ForeignKey(User,
                             blank=True,
                             null=True,
                             on_delete=models.SET_NULL
                             )
    content = models.CharField(max_length=1000)
    likes = models.ManyToManyField(User,related_name='spot_likes')

    def __str__(self):
        return f"{self.title[:10]} - {self.content[:10]}"



class Meme(models.Model):
    title = models.CharField(validators=[MinLengthValidator(5)], max_length=70)
    pub_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,
                             blank=True,
                             null=True,
                             on_delete=models.SET_NULL
                             )

    admin_aproved = models.BooleanField(default=False)
    image = models.ImageField(
        validators=[validate_size,validate_shape], upload_to='memes/'
    )


class CommentSpot(models.Model):
    spot = models.ForeignKey(Spot,blank=True,
                             null=True,on_delete=models.CASCADE)
    user = models.ForeignKey(User,
                             blank=True,
                             null=True,
                             on_delete=models.SET_NULL
                             )
    pub_date = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.content[:10]}"


class CommentMeme(models.Model):
    meme = models.ForeignKey(Meme,blank=True,
                             null=True,on_delete=models.CASCADE)
    user = models.ForeignKey(User,
                             blank=True,
                             null=True,
                             on_delete=models.SET_NULL
                             )
    pub_date = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.content[:10]}"

ms_web/msagh_website/forms.py
from django import forms
from .models import Spot,Meme,CommentSpot,CommentMeme


class SpotForm(forms.ModelForm):
    class Meta:
        model = Spot
        fields = ['title',
                  'content',
                  ]

        labels = {
            'title': 'Tytuł',
            'content': 'Treść'
        }

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-group'}),
            'content': forms.Textarea(attrs={'class': 'form-group'})

        }


class MemeForm(forms.ModelForm):
    class Meta:
        model = Meme
        fields = ['title',
                  'image'

                  ]

        labels = {
            'title': 'Tytuł',
            'image': 'Mem'

        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-group'}),


        }

class CommentSpotForm(forms.ModelForm):
    class Meta:
        model = CommentSpot
        fields = ['content']
        widgets = {

            'content': forms.Textarea(attrs={'rows': 4, 'cols': 70,},)

        }

class CommentMemeForm(forms.ModelForm):
    class Meta:
        model = CommentMeme
        fields = ['content']
        widgets = {

            'content': forms.Textarea(attrs={'rows': 4, 'cols': 70,},)

        }

ms_web/msagh_website/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from .forms import SpotForm, MemeForm, CommentSpotForm, CommentMemeForm
from .models import Spot, Meme, CommentSpot, CommentMeme
from django.core.paginator import Paginator
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib import messages  # import messages
from ms_web.settings import EMAIL_FROM_ADDRESS

from datetime import timedelta
from ratelimit.decorators import ratelimit
from blacklist.ratelimit import blacklist_ratelimited


# Create your views here.

def base(request):
    posts_list = Spot.objects.all().filter(admin_aproved=True).order_by('-pub_date')[:3]
    first_post = posts_list[0]
    second_post = posts_list[1]
    third_post = posts_list[2]

    return render(request, 'base.html', {'first_post': first_post,
                                         'second_post': second_post,
                                         'third_post': third_post, })


def spotted(request):
    # Handling with like form
    if request.method == 'POST':
        if request.user.is_authenticated:
            # Grabbing post pk from form value
            pk = request.POST.get('like_form')
            # Grabbing single post
            single_spot = Spot.objects.all().filter(admin_aproved=True).get(pk=pk)
            # Checking if post was already liked
            if single_spot.likes.filter(pk=request.user.pk).exists():
                messages.warning(request, 'Już zareagowałeś na ten post!')

            else:
                # Adding like if post was not liked before
                single_spot.likes.add(request.user)
                # Grabing current pagination page
                act_page = request.GET.get('page')
                # Redirecting to particular pagination page
                url = reverse('msagh_website:spotted')
                url += f'?page={act_page}'
                return redirect(url)
        else:
            messages.warning(request, 'Musisz się zalogować aby zareagować na post!')

    # look only for approved posts and order them by publication date
    posts_list = Spot.objects.all().filter(admin_aproved=True).order_by('-pub_date')

    # Set up Paginator
    p = Paginator(posts_list, 4)
    page = request.GET.get('page')
    posts = p.get_page(page)

    # list of numbers of comments and likes for every spot:
    numbers = []
    likes = []
    for post in posts:
        comments = CommentSpot.objects.all().filter(spot=post)
        numbers.append(len(comments))
        likes.append(post.likes.count())
    # number of last page to show ( ... ) in html of spotted in paginator
    last_page = p.get_page(-1).number

    numbers_posts = zip(numbers, posts, likes)  # zip to iterate into django template
    return render(request, 'msagh_website/spotted.html', {'posts': posts,
                                                          "numbers_posts": numbers_posts,
                                                          "last_page": last_page})

# If user send more than 50 requests/h block him for 3 hours
# code below need two packages ratelimit and blacklist
@ratelimit(key='user', rate='50/h', block=False)
@blacklist_ratelimited(timedelta(minutes=180))
@login_required(login_url='/login')
def new_spot(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SpotForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            form = SpotForm()
            return render(request, 'msagh_website/success_post_spot.html')

        # if a GET (or any other method) we'll create a blank form
    else:
        form = SpotForm()
    return render(request, 'msagh_website/new_spot.html', context={'form': form})


def memes(request):
    # look only for approved posts and order them by publication date
    memes_list = Meme.objects.all().filter(admin_aproved=True).order_by('-pub_date')

    # Set up Paginator
    p = Paginator(memes_list, 5)
    page = request.GET.get('page')
    memes = p.get_page(page)

    # list of numbers of comments for every spot:
    numbers = []
    for meme in memes:
        comments = CommentMeme.objects.all().filter(meme=meme)
        numbers.append(len(comments))
    # number of last page to show ( ... ) in html of spotted in paginator
    last_page = p.get_page(-1).number
    numbers_memes = zip(numbers, memes)  # zip to iterate into django template
    return render(request, 'msagh_website/memes.html', {'memes': memes,
                                                        "last_page": last_page,
                                                        "numbers_memes": numbers_memes
                                                        })


# if user send more than 50 request/hour block him for 8 hours
@ratelimit(key='user', rate='50/h', block=False)
@blacklist_ratelimited(timedelta(minutes=480))
@login_required(login_url='/login')
def new_meme(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = MemeForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()

            return render(request, 'msagh_website/success_post_spot.html')

        # if a GET (or any other method) we'll create a blank form
    else:
        form = MemeForm()
    return render(request, 'msagh_website/new_meme.html', context={'form': form})


def contact(request):
    return render(request, 'msagh_website/contact.html')


def password_reset_request(request):
    if request.user.is_authenticated:
        return redirect(reverse('msagh_website:base'))  # Prevent logged user to reset password by type in browser

    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']  # Getting email from form
            associated_users = User.objects.filter(
                Q(email=data, is_active=True))  # Checking if user with that email exists
            if associated_users.exists():
                try:
                    # Trying send email with link to reset password by built function
                    password_reset_form.save(domain_override='139.162.139.50:8000',
                                             subject_template_name='password/password_reset_email.txt',
                                             html_email_template_name='password/password_reset_body.html',
                                             from_email=EMAIL_FROM_ADDRESS)
                    return render(request, 'msagh_website/success_reset_password_sent.html')
                except:
                    # Warning if something went wrong
                    messages.warning(request, 'Coś poszło nie tak... spróbuj jeszcze raz.')

            else:
                # Warning if user with that email do not exist
                messages.warning(request,
                                 "Nie znaleźliśmy żadnego konta powiązanego z tym adresem Email, sprawdź swoje dane i spróbuj jeszcze raz."
                                 " Jeśli jeszcze tego nie zrobiłeś, potwierdź swoje konto.")

    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


@ratelimit(key='user', rate='60/h', block=False)
@blacklist_ratelimited(timedelta(minutes=480))
def one_spot(request, pk):
    try:
        single_spot = Spot.objects.all().filter(admin_aproved=True).order_by('pub_date').get(pk=pk)
    except Spot.DoesNotExist:
        return redirect(reverse('msagh_website:spotted'))

    if request.method == 'POST':

        if request.user.is_authenticated:
            # Checking which form was sent. Here Like form
            if request.POST.get('like_form') == 'like_form':
                # initalizing comment_form in order to avoid error
                form = CommentSpotForm(request.POST)
                # Checking if post was already liked
                if single_spot.likes.filter(pk=request.user.pk).exists():
                    messages.warning(request, 'Już zareagowałeś na ten post!')
                else:
                    # Adding like if post was not liked before
                    single_spot.likes.add(request.user)
                    return redirect(reverse('msagh_website:one_spot', args=(pk,)))

            # Comment form
            else:
                # create a form instance and populate it with data from the request:
                form = CommentSpotForm(request.POST)
                # check whether it's valid:
                if form.is_valid():
                    obj = form.save(commit=False)
                    obj.user = request.user
                    obj.spot = single_spot

                    obj.save()
                    return redirect(reverse('msagh_website:one_spot', args=(pk,)))
        else:
            messages.warning(request, 'Musisz się zalogować aby wykonać tą akcję!')
            return redirect(reverse('msagh_website:one_spot', args=(pk,)))
    else:

        form = CommentSpotForm()

    comments = CommentSpot.objects.all().filter(spot=single_spot)
    no_comments = len(comments)

ms_web/msagh_website/templates/msagh_website/memes.html
{% extends "base.html"%}

{%block content%}
<style>
  .cosik {
    /*align: right;*/
    /*text-align: right;*/
    position: relative;
      allign : left;
      top : 47px;


}

</style>

<h1></h1>
<h1 class="mb-3" align="center">Najnowsze memy

  <div class="cosik">
<!--  <button type="button" class="btn btn-dark">Dodaj nowy spot</button>-->
    <a href="{% url 'msagh_website:new_meme' %}" class="btn btn-dark" role="button">Dodaj nowy mem</a>
</div>
</h1>

<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
<div class="container"  bgcolor=”#802003" align="center" >
      <div>

        <div class="col-lg-9 mb-3" >
          <div class="row text-left mb-5">
            <div class="col-lg-6 mb-3 mb-sm-0">
            </div>
          </div>

    {% for number, meme in numbers_memes %}
        {% if meme.admin_aproved %}
    <div class="card row-hover pos-relative py-3 px-3 mb-3 border-warning border-top-3 border-right-3 border-bottom-3 " align="center" border-="red" >
            <div class="row align-items-center">
              <div class="col-md-12 mb-3 mb-sm-0">
                <h5>
                  <div align="center">
                    <h8><a style="text-decoration: none; color: black" href="{% url 'msagh_website:one_meme' meme.pk %}">{{ meme.title }}</a></h8>
                  </div>
                </h5>
                {% if meme.user %}
                      <p class="text-sm"><span class="op-6">Dodane</span> {{ meme.pub_date }}</a> przez <a href="{% url 'members:profile' meme.user.pk %}" style="text-decoration: none; color: #423a3a"> <b>{{ meme.user }}</b></a> </p>

                  {% else %}
                  <p class="text-sm"><span class="op-6">Dodane</span> {{ meme.pub_date }}</a> przez Użytkownik usunięty </p>

                  {% endif %}
                <a  href="{% url 'msagh_website:one_meme' meme.pk %}">
                    <img src='{{ meme.image.url }}' />
                </a>

              </div>
<div style="margin-top: 20px" class="row text-center op-7">
                  <div class="col px-1"> <i style="font-size:24px" class="fa">&#xf0e6;</i> <span class="d-block text-sm"> {{ number }} komentarzy</span> </div>
                </div>


            </div>
          </div>

        {% endif %}
    {% endfor %}


    <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if memes.has_previous %}
      <li class="page-item ">
      <a class="page-link" href="?page={{ memes.previous_page_number }}">Poprzedni</a>
          {% if memes.number > 2 %}
       <li class="page-item disabled"><a class="page-link" href="?page={{ memes.number }}"> ... </a></li>
          {% endif %}
    <li class="page-item "><a class="page-link" href="?page={{ memes.previous_page_number }}">{{ memes.previous_page_number }}</a></li>
      </li>
        {% else %}
        <li class="page-item disabled ">
      <a class="page-link" href="">Poprzedni</a>
        </li>
    {% endif %}


    <li class="page-item active ">
        <a class="page-link" href="?page={{ memes.number }}">{{ memes.number }}<span class="sr-only"></span></a>
    </li>



    {% if memes.has_next %}
      <li class="page-item ">
      <li class="page-item "><a class="page-link" href="?page={{ memes.next_page_number }}">{{ memes.next_page_number }}</a></li>
      {% if memes.next_page_number != last_page %}
    <li class="page-item disabled"><a class="page-link" href="?page={{ memes.number }}">  ... </a></li>
          {% endif %}
      <a class="page-link" href="?page={{ memes.next_page_number }}">Kolejny</a>
      </li>
        {% else %}
        <li class="page-item disabled ">
      <a class="page-link" href="">Kolejny</a>
        </li>
    {% endif %}


</nav>
            {%endblock content%}

ms_web/msagh_website/templates/msagh_website/new_meme.html
{% extends "base.html"%}

{%block content%}
<style>


        input{

        outline: none !important;
        border-color: #719ECE;
        box-shadow: 0 0 10px #719ECE;

    }
                                                                    {#Adding pretty shadow to title and content area#}



        .form-group {
margin: auto;
            margin-top: 20px;

width: 65%;
    text-align: center;
    user-input: center;

padding: 6px;
}
        #id_title{
    display: table;
    margin: 0 auto;
    border: 1px solid black;
}



.asteriskField {
    display: none;                      {#Deleting * from label#}
}
        button{
            margin-top: 10px;
            align-content: center;
            outline: none !important;
        border-color: #719ECE;
        box-shadow: 0 0 10px #719ECE;
        }
    </style>



    <body>
{% load crispy_forms_tags %}
{% load static %}
<h1>

</h1>
            <div class="container" align="center">
                <img src="{% static 'msagh_website/images/alfaXD.png' %}" alt="Dupa" height="180" width="200">
            </div>

<form class="form-group" method="post" enctype="multipart/form-data">
     {% csrf_token %}
    {{form | crispy}}
    <p> Przeciągnij obrazek powyżej</p>
    <button type="submit" class="btn btn-dark">Dodaj mema</button>
</form>
</body>
</html>
{%endblock content%}

ms_web/msagh_website/templates/msagh_website/new_spot.html
{% extends "base.html"%}

{%block content%}

    <style>


        input{

        outline: none !important;
        border-color: #719ECE;
        box-shadow: 0 0 10px #719ECE;

    }
                                                                    {#Adding pretty shadow to title and content area#}

       textarea {
        outline: none !important;
        border-color: #719ECE;
        box-shadow: 0 0 10px #719ECE;
           border:1px solid red;
           outline-color: #000000;
           margin-bottom: 20px;
    }


        .form-group {
margin: auto;

width: 72%;
    text-align: center;
    user-input: center;

padding: 6px;
}
        #id_title{
    display: table;
    margin: 0 auto;
    border: 1px solid black;
}
     #id_content{
    border: 1px solid black;
}


.asteriskField {
    display: none;                      {#Deleting * from label#}
}
        button{
            margin-top: 10px;
            align-content: center;
            outline: none !important;
        border-color: #719ECE;
        box-shadow: 0 0 10px #719ECE;
        }
    </style>

{% load crispy_forms_tags %}

   <form method="post" class="form-group" >
    {% csrf_token %}
   <div class="form-group col-md-6 mb-0">
        {{ form.title|as_crispy_field }}
      </div>
    <div class="form-group col-md-6 mb-0">
        {{ form.content|as_crispy_field }}
        <button type="submit" class="btn btn-dark">Dodaj Post</button>
      </div>

  </form>

{%endblock content%}

ms_web/msagh_website/templates/msagh_website/one_meme.html
{% extends 'base.html' %}

{% block content %}

<style>
body {
    background-image: none;
  background-color: #f8f9fa;
}
.cosik {
    position: relative;
      allign : left;
      top : 47px;


  }

.center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  height: 100px;
    width: 150px;
}

.form-group {

width: 100%;
    height: 50%;
    text-align: center;
    user-input: center;

padding: 1px;
}

</style>

<div class="container"  bgcolor=”#802003" align="center" >
      <div>

        <div class="col-lg-9 mb-3" >
          <div class="row text-left mb-5">
            <div class="col-lg-6 mb-3 mb-sm-0">
            </div>
          </div>

             <div class="card row-hover pos-relative py-3 px-3 mb-3 border-warning border-top-3 border-right-3 border-bottom-3 " align="center" border-="red" >
            <div class="row align-items-center">
              <div class="col-md-12 mb-3 mb-sm-0">
                <h5>
                  <div align="center">
                    <h8>{{ single_meme.title }}</h8>
                  </div>
                </h5>

                  {% if single_meme.user %}

                <p class="text-sm"><span class="op-6">Dodane</span> {{ single_meme.pub_date }} przez <a href="{% url 'members:profile' single_meme.user.pk %}" style="text-decoration: none; color: #423a3a"> <b>{{ single_meme.user }}</b></a> </p>
                  {% else %}

                  <p class="text-sm"><span class="op-6">Dodane</span> {{ single_meme.pub_date }} przez Użytkownik usunięty </p>
                  {% endif %}
                    <img src='{{ single_meme.image.url }}' />
                  <div style="margin-top: 12px" class="col px-1"> <i style="font-size:24px" class="fa">&#xf0e6;</i> <span class="d-block text-sm"> {{ no_comments }} komentarzy</span> </div>


              </div>

            </div>
          </div>

                 {% load crispy_forms_tags %}

   <form method="post" class="form-group" >
    {% csrf_token %}
   <div class="form-group col-md-6 mb-0">
        {{ form.content }}
      </div>
    <div class="form-group col-md-6 mb-0">

        <button type="submit" class="btn btn-dark">Dodaj Komentarz</button>
      </div>

  </form>


<h2 style="margin: 20px">Ostatnie komentarze</h2>
        <hr>

    <div class="row d-flex justify-content-center">
        <div class="col-md-8">


        {% for comment in comments %}


            <div class="headings d-flex justify-content-between align-items-center mb-3">

            </div>
            <div class="card p-3 border-0 bg-light ">
                <div class="d-flex justify-content-between align-items-center">

                    {% if comment.user %}
                    <div class="user d-flex flex-row align-items-center">  <span><small class="font-weight-bold text-dark"><h6><a href="{% url 'members:profile' comment.user.pk %}" style="text-decoration: none; color: #423a3a"> {{ comment.user }}</a></h6></small>  </div> <small>{{comment.pub_date}}</small></span>

                    {% else %}

                    <div class="user d-flex flex-row align-items-center">  <span><small class="font-weight-bold text-dark"><h6 style="font-weight: normal">Użytkownik usunięty</h6></small>  </div> <small>{{comment.pub_date}}</small></span>

                    {% endif %}
                </div>
                <hr size='3' style="margin-top: 1px; ">

                <div style="margin-top: 2px" align="left" ><small class="font-weight-bold">{{ comment.content}}</small></div>
                <div class="action d-flex justify-content-between mt-2 align-items-center">

                </div>
            </div>




{% endfor %}

     </div>
    </div>


{% endblock %}

ms_web/msagh_website/templates/msagh_website/spotted.html
{% extends "base.html"%}
{%block content%}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<style>
  .cosik {
    /*align: right;*/
    /*text-align: right;*/
    position: relative;
      allign : left;
      top : 47px;


}
  {#remove focus around buttons on click#}
  .btn:focus {
  outline: none;
  box-shadow: none;
}

</style>

<h1></h1>
<h1 class="mb-3" align="center">Najnowsze spoty

  <div class="cosik">
<!--  <button type="button" class="btn btn-dark">Dodaj nowy spot</button>-->
    <a href="{% url 'msagh_website:new_spot' %}" class="btn btn-dark" role="button">Dodaj nowy spot</a>
</div>
</h1>


<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
<div class="container"  bgcolor=”#802003" align="center" >
      <div>

        <div class="col-lg-9 mb-3" >
          <div class="row text-left mb-5">
            <div class="col-lg-6 mb-3 mb-sm-0">
            </div>
          </div>

    {% for number, post, like in numbers_posts %}
        {% if post.admin_aproved %}
    <div class="card row-hover pos-relative py-3 px-3 mb-3 border-warning border-top-3 border-right-3 border-bottom-3 rounded-10 width-4" align="left" border-="red" >
            <div class="row align-items-center">
              <div class="col-md-8 mb-3 mb-sm-0">
                <h5>
                  <div>
                   <a href="{% url 'msagh_website:one_spot' post.pk %}">{{ post.title }}</a>
                  </div>
                </h5>
                  {% if post.user %}
                      <p class="text-sm"><span class="op-6">Dodane</span> {{ post.pub_date }}</a> przez <a href="{% url 'members:profile' post.user.pk %}" style="text-decoration: none; color: #423a3a"> <b>{{ post.user }}</b></a> </p>
                <h8>{{ post.content }}</h8>
                  {% else %}
                  <p class="text-sm"><span class="op-6">Dodane</span> {{ post.pub_date }}</a> przez Użytkownik usunięty </p>
                <h8>{{ post.content }}</h8>
                  {% endif %}

              </div>
              <div class="col-md-4 op-7">
                <div class="row text-center op-7">
                  <div class="col px-1"> <i style="font-size:24px" class="fa">&#xf0e6;</i> <span class="d-block text-sm"> {{ number }} komentarzy</span> </div>

                <form method="POST">
                {% csrf_token %}

            <input type="hidden" name="like_form", value={{ post.pk }}>
            <button type="submit" class="btn btn-small"  ><i style="font-size: 24px; margin-right: -10px" class="fa fa-plus"></i></button>
                    +{{ like }}
        </form>
                </div>
              </div>
            </div>
          </div>
        {% endif %}
    {% endfor %}
          <!-- /End of post 2 -->
          <!-- End of post 3 -->




    <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if posts.has_previous %}
      <li class="page-item ">
      <a class="page-link" href="?page={{ posts.previous_page_number }}">Poprzedni</a>
          {% if posts.number > 2 %}
       <li class="page-item disabled"><a class="page-link" href="?page={{ posts.number }}"> ... </a></li>
          {% endif %}
    <li class="page-item "><a class="page-link" href="?page={{ posts.previous_page_number }}">{{ posts.previous_page_number }}</a></li>
      </li>
        {% else %}
        <li class="page-item disabled ">
      <a class="page-link" href="">Poprzedni</a>
        </li>
    {% endif %}


    <li class="page-item active ">
        <a class="page-link" href="?page={{ posts.number }}">{{ posts.number }}<span class="sr-only"></span></a>
    </li>



    {% if posts.has_next %}
      <li class="page-item ">
      <li class="page-item "><a class="page-link" href="?page={{ posts.next_page_number }}">{{ posts.next_page_number }}</a></li>
      {% if posts.next_page_number != last_page %}
    <li class="page-item disabled"><a class="page-link" href="?page={{ posts.number }}">  ... </a></li>
          {% endif %}
      <a class="page-link" href="?page={{ posts.next_page_number }}">Kolejny</a>
      </li>
        {% else %}
        <li class="page-item disabled ">
      <a class="page-link" href="">Kolejny</a>
        </li>
    {% endif %}


</nav>




{%endblock content%}

ms_web/msagh_website/templates/msagh_website/success_reset_password_sent.html
{% extends 'base.html' %}


{% block content %}

</style>
</head>
<body>


<div class="alert alert-success" role="alert">
  Wysłaliśmy na twojego maila instrukcję do zresetowania hasła, kliknij w link aby zmienić swoje hasło. <a href="/" class="alert-link">Strona główna</a>.
</div>

</body>
</html>


{% endblock %}