ms_web/members/urls.py
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path('',views.register,name='register'),
    path('logout/',views.logoutUser,name='logout'),
    path('profile/<int:pk>',views.profile, name='profile'),
    path('profile/edit_profile',views.edit_profile,name='edit_profile'),
    path('profile/edit_profile/password_change',views.password_change,name='password_change')
]

ms_web/ms_web/urls.py
from django.contrib import admin
#from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls
from django.views.static import serve

urlpatterns = [
                  path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
                  path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
                  path('admin/', admin.site.urls),
                  path('', include('msagh_website.urls')),
                  path('members/', include('members.urls')),
                  path('', include("django.contrib.auth.urls")),
                  path('email/', include(email_urls)),  # verification user path
              # 	path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
#path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
              ]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # Operation for images in meme section


handler404 = 'ms_web.views.handle_not_found'

ms_web/msagh_website/urls.py
from django.urls import path
from. import views
from django.contrib.auth import views as auth_views #import this

app_name = "msagh_website"

urlpatterns = [
    path('',views.base,name='base'),
    path('spotted/<int:pk>', views.one_spot, name="one_spot"),
    path('spotted/', views.spotted, name='spotted'),
    path('new_spot', views.new_spot, name="new_spot"),
    # path('memes/', views.memes, name="memes"),
    # path('memes/<int:pk>', views.one_meme, name="one_meme"),
    # path('new_meme/',views.new_meme,name='new_meme'),
    path('contact/', views.contact, name="contact"),
    path("password_reset/", views.password_reset_request, name="password_reset"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    # URL connected with passsword
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),

]

ms_web/templates/banned_user.html
{% extends "base.html"%}
{%block content%}
<style>




.txt1 {color: #0070BB;
	font-size: 40px;
  font-weight: 800;
	text-align: center;
	margin-top: 20px; }

.txt2 {color: #c8c6ce;
	font-size: 18px;
	text-align: center;
	margin-top: 20px; }

.txt3 {color: #c8c6ce;
	font-size: 18px;
	text-align: center;
	margin-top: 20px; }

.logo {
text-align: center;
  margin-top: 10px; }

.button {
    border: 2px solid none;
    padding: 10px 40px;
    background: #0070BB;
   color: white;
	text-align: center;
	width: 300px;
    border-radius: 25px;
	margin: 20px auto;
	transition: all 0.3s ease 0s;
	-webkit-box-shadow: 0px 11px 20px -8px rgba(0,112,187,1);
	-moz-box-shadow: 0px 11px 20px -8px rgba(0,112,187,1);
	box-shadow: 0px 11px 20px -8px rgba(0,112,187,1);}

.button:hover {
    border: 2px solid none;
    padding: 10px 40px;
    background: #0070BB;
  color: white;
	text-align: center;
	width: 300px;
    border-radius: 25px;
    margin: 5px auto;
	transition: all 0.3s ease 0s;
	-webkit-box-shadow: 0px 19px 34px -8px rgba(0,112,187,1);
	-moz-box-shadow: 0px 19px 34px -8px rgba(0,112,187,1);
	box-shadow: 0px 19px 34px -8px rgba(0,112,187,1);}

a .button {
	color: ffffff;
	text-align: center;
	font-size: 16px;
	text-decoration: none;
}

a {text-decoration: none;}
a:hover {text-decoration: none;}

#orbit-system {
  position: relative;
  width: 18em;
  height: 18em;
  margin: 0px auto;
}

.system {
  position: relative;
  width: 100%;
  height: 100%;

  -webkit-transform: rotateX(75deg) rotateY(-30deg);
  transform: rotateX(75deg) rotateY(-30deg);
  -webkit-transform-style: preserve-3d;
  transform-style: preserve-3d;
}

.planet, .satellite-orbit, .satellite {
  position: absolute;
  top: 50%;
  left: 50%;

  -webkit-transform-style: preserve-3d;
  transform-style: preserve-3d;
}

.planet {
  width: 9em;
  height: 9em;
  margin-top: -20em;
  margin-left: -4.5em;

  border-radius: 50%;
  background-color: none;
  color: white;

  text-align: center;
  line-height: 9em;

  -webkit-transform: rotateY(30deg) rotateX(-75deg);
  transform: rotateY(30deg) rotateX(-75deg);
}

.satellite-orbit {
	width: 16em;
  height: 16em;
  margin-top: -8em;
  margin-left: -8em;

  /*border: 1px solid black;*/
  border-radius: 50%;

  -webkit-animation-name: orbit;
  animation-name: orbit;
  -webkit-animation-duration: 10s;
  animation-duration: 10s;
  -webkit-animation-iteration-count: infinite;
  animation-iteration-count: infinite;
  -webkit-animation-timing-function: linear;
  animation-timing-function: linear;
}

.satellite {
    top: 100%;
    width: 7em;
    height: 7em;
    margin-top: -1.5em;
    margin-left: -1.5em;
    color: #fefefe;
    background-color: #0070BB;
    border-radius: 50%;
    text-align: center;
    font-weight: 600;
    line-height: 7em;
    -webkit-animation-name: invert-orbit;
    animation-name: invert-orbit;
    -webkit-animation-duration: 3s;
    animation-duration: 3s;
    -webkit-animation-iteration-count: infinite;
    animation-iteration-count: infinite;
    -webkit-animation-timing-function: linear;
    animation-timing-function: linear;
}

@-webkit-keyframes orbit {
    0% {
        transform: rotateZ(0deg);
    }
    100% {
        transform: rotateZ(360deg);
    }
}
@keyframes orbit {
    0% {
        transform: rotateZ(0deg);
    }
    100% {
        transform: rotateZ(360deg);
    }


}

/*
In order to invert the rotation, do the rotate* transforms in reverse order.

Here, we rotated the system with rotateX(75deg) rotateY(-30deg), and then we are animating the rotation of the orbit with rotateZ(0-360deg). To reverse that, we need to reverse the last transform applied (rotateZ), then rotateY, then rotateX.

The rotateX/Y reversal is easy since it's not animated, so just use its opposite (30deg, -75deg). The rotateZ is trickier since it's animating, but since it's rotating from 0 to 360, we just need to animate the satellite from 360 to 0.
*/
@-webkit-keyframes invert-orbit {
    0% {
        transform: rotateZ(360deg) rotateY(30deg) rotateX(-75deg);
    }

    100% {
        transform: rotateZ(0deg) rotateY(30deg) rotateX(-75deg);
    }
}
@keyframes invert-orbit {
    0% {
        transform: rotateZ(360deg) rotateY(30deg) rotateX(-75deg);
    }

    100% {
        transform: rotateZ(0deg) rotateY(30deg) rotateX(-75deg);
    }
}
</style>

<body>
<html>
<head>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
<div class="txt1 center">Konto zostało zablokowane!</div>
<div class="txt2">Konto {{ user.username }} zostało zablokowane przez administratora!</div>
<div id="orbit-system">
  <div class="system">
    <div class="satellite-orbit">
      <div class="satellite">SUSPENDED</div>
    </div>
    <div class="planet"><img src="http://orig02.deviantart.net/69ab/f/2013/106/0/4/sad_man_by_agiq-d61wk0d.png" height="200px"> </div>
  </div>
</div>
<div class="txt3">W celu uzyskania informacji napisz na telegramie: </div>
<a href="https://t.me/tomal13"><div class="button">Napisz do nas na Telegramie</div></a>
</body>
</html>
</body>
{%endblock content%}

ms_web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MS AGH Spotted</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'msagh_website/images/alfaXD.png' %}">
  <style>
     body  {
background-image: url({% static 'msagh_website/images/background_image.jpg' %});
}


      h8{
            color: #000000;
            font-size:18px;
    }
      .allspots {

  /* Center vertically */
  position: relative;
        text-align: center;
}

        </style>
</head>
<body>

<!-- NAVBAR -->


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'msagh_website:base' %}">Strona główna</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'msagh_website:spotted' %}">Spotted</a>
        </li>
{#        <li class="nav-item">#}
{#          <a class="nav-link active" href="{% url 'msagh_website:memes' %}">Sekcja memów</a>#}
{#        </li>#}
                <li class="nav-item">
          <a class="nav-link active" href="{% url 'msagh_website:contact' %}">Kontakt</a>
        </li>

        </li>

      </ul>
        <div>
                            {% if user.is_authenticated and request.user.profile is not None %}
        <a href="{% url 'members:edit_profile' %}" class="btn btn-dark" role="button">Edytuj Profil</a>
        <a href="{% url 'members:profile' request.user.pk %}" class="btn btn-dark" role="button"> <i class='fas fa-user-alt' style='font-size:18px'></i>  {{ user.username }}</a>
        {% endif %}
        </div>

        {% if user.is_authenticated %}
        <a href="{% url 'members:logout' %}" class="btn btn-dark" role="button">Wyloguj</a>
            {% else %}
            <a href="/login/" class="btn btn-dark" role="button">Zaloguj sie</a>

        {% endif %}

    </div>

  </div>
</nav>
{% include 'includes/messages.html' %}
{%block content%}


<main class="container">

    <div style="margin: 20px"  align="center" >
    <img  src="{% static 'msagh_website/images/alfaXD.png' %}" alt="Dupa" height="180" width="200">
    </div>
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0"><i style="font-size:24px" class="fa">&#xf1ea;</i> Ostatnie spoty</h6>
    <div class="d-flex text-muted pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>

      <p class="pb-3 mb-0  lh-sm ">
        {% if first_post.user != None %}
          <strong class="d-block text-gray-dark"><a href="{% url 'members:profile' first_post.user.pk %}" style="text-decoration: none; color: #423a3a">{{first_post.user}}</a></strong>
        {% else %}
          <strong class="d-block text-gray-dark"> Użytkownik usunięty </strong>
        {% endif %}
    <a href="{% url 'msagh_website:one_spot' first_post.pk %}">{{ first_post.title}}</a>
      </p>
    </div>
    <div class="d-flex text-muted pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#e83e8c"/><text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text></svg>

      <p class="pb-3 mb-0  lh-sm ">
        {% if second_post.user != None %}
          <strong class="d-block text-gray-dark"><a href="{% url 'members:profile' second_post.user.pk %}" style="text-decoration: none; color: #423a3a">{{second_post.user}}</a></strong>
        {% else %}
          <strong class="d-block text-gray-dark"> Użytkownik usunięty </strong>
        {% endif %}
        <a href="{% url 'msagh_website:one_spot' second_post.pk %}">{{ second_post.title}}</a>
      </p>
    </div>
    <div class="d-flex text-muted pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#6f42c1"/><text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text></svg>

      <p class="pb-3 mb-0  lh-sm ">
        {% if third_post.user != None %}
          <strong class="d-block text-gray-dark"><a href="{% url 'members:profile' third_post.user.pk %}" style="text-decoration: none; color: #423a3a" >{{third_post.user}}</a></strong>
        {% else %}
          <strong class="d-block text-gray-dark"> Użytkownik usunięty </strong>
        {% endif %}
        <a href="{% url 'msagh_website:one_spot' third_post.pk %}">{{ third_post.title}}</a>

      </p>
    </div>
    <small class="center">
      <div class = "allspots">
              <a href="{% url 'msagh_website:spotted' %}">Wszystkie Spoty</a>
      </div>
    </small>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0"><i class="fa fa-graduation-cap" style="font-size:27px"></i> Administracja poleca</h6>

      <div class="d-flex text-muted pt-3">
<p><i class="fas fa-infinity fa-spin" style="font-size:27px; color: black; margin-right: 5px"></i></p>
      <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <div class="d-flex justify-content-between">
          <strong class="text-gray-dark">Algebra liniowa</strong>
        </div>
        <a href="https://home.agh.edu.pl/~gora/">Rewelacyjne materiały do Algebry liniowej (i nie tylko)</a>
      </div>
    </div>
    <div class="d-flex text-muted pt-3">
<p><i class="fas fa-infinity fa-spin" style="font-size:27px; color: black; margin-right: 5px"></i></p>
        <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <div class="d-flex justify-content-between">

          <strong class="text-gray-dark">Teoria macierzy Jordana</strong>
        </div>
        <a href="https://www.youtube.com/watch?v=iGQg3iAxbT4&ab_channel=MateuszKowalski">Rozwiązania kilku przykładów</a>
      </div>
    </div>
    <div class="d-flex text-muted pt-3">
<p><i class="fas fa-infinity fa-spin" style="font-size:27px; color: black; margin-right: 5px"></i></p>
      <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <div class="d-flex justify-content-between">
          <strong class="text-gray-dark">Metody numeryczne</strong>
        </div>
        <a href="https://github.com/KAIR-ISZ/public_lectures/tree/master/Metody%20Numeryczne%202021">Teoria do zagadnień metod numerycznych</a>

      </div>
    </div>
    <small class="d-block text-end mt-3">
    </small>
  </div>
</main>


    <script src="/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

      <script src="offcanvas.js"></script>
{%endblock content%}


</body>
</html>

ms_web/templates/confirm_template.html
{% extends "base.html"%}
{%block content%}

<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

{% if success %}
<div class="alert alert-success d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    Witaj {{ user.username }}, Twoje konto zostało potwierdzone i jest już aktywne! Przejdź do strony głównej: <a href="/" class="alert-link">Strona główna</a>
  </div>
</div>
{% else %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
  <div>
    Coś poszło nie tak, link aktywacyjny się przedawnił, konto nie zostało aktywowane!
  </div>
</div>
{% endif %}
</body>
</html>

{%endblock content%}

ms_web/templates/mail_body.html
<!DOCTYPE html>
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<style type="text/css">
@media screen {
@font-face {
font-family: 'Lato';
font-style: normal;
font-weight: 400;
src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v11/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');
}
@font-face {
font-family: 'Lato';
font-style: normal;
font-weight: 700;
src: local('Lato Bold'), local('Lato-Bold'), url(https://fonts.gstatic.com/s/lato/v11/qdgUG4U09HnJwhYI-uK18wLUuEpTyoUstqEm5AMlJo4.woff) format('woff');
}
@font-face {
font-family: 'Lato';
font-style: italic;
font-weight: 400;
src: local('Lato Italic'), local('Lato-Italic'), url(https://fonts.gstatic.com/s/lato/v11/RYyZNoeFgb0l7W3Vu1aSWOvvDin1pK8aKteLpeZ5c0A.woff) format('woff');
}
@font-face {
font-family: 'Lato';
font-style: italic;
font-weight: 700;
src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url(https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYELO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');
}
}
/* CLIENT-SPECIFIC STYLES */
body,
table,
td,
a {
-webkit-text-size-adjust: 100%;
-ms-text-size-adjust: 100%;
}
table,
td {
mso-table-lspace: 0pt;
mso-table-rspace: 0pt;
}
img {
-ms-interpolation-mode: bicubic;
}
/* RESET STYLES */
img {
border: 0;
height: auto;
line-height: 100%;
outline: none;
text-decoration: none;
}
table {
border-collapse: collapse !important;
}
body {
height: 100% !important;
margin: 0 !important;
padding: 0 !important;
width: 100% !important;
}
/* iOS BLUE LINKS */
a[x-apple-data-detectors] {
color: inherit !important;
text-decoration: none !important;
font-size: inherit !important;
font-family: inherit !important;
font-weight: inherit !important;
line-height: inherit !important;
}
/* MOBILE STYLES */
@media screen and (max-width:600px) {
h1 {
font-size: 32px !important;
line-height: 32px !important;
}
}
/* ANDROID CENTER FIX */
div[style*="margin: 16px 0;"] {
margin: 0 !important;
}
</style>
</head>
<body style="background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;">
<!-- HIDDEN PREHEADER TEXT -->

<div style="display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: 'Lato', Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;"> We're thrilled to have you here! Get ready to dive into your new account. </div>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<!-- LOGO -->
<tr>
<td bgcolor="#FFA73B" align="center">
<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
<tr>
<td align="center" valign="top" style="padding: 40px 10px 40px 10px;"> </td>
</tr>
</table>
</td>
</tr>
<tr>
<td bgcolor="#FFA73B" align="center" style="padding: 0px 10px 0px 10px;">
<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
<tr>
<td bgcolor="#ffffff" align="center" valign="top" style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">

    <h1 style="font-size: 48px; font-weight: 400; margin: 2;">Witaj {{ user.username }} na pokładzie!</h1>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td bgcolor="#f4f4f4" align="center" style="padding: 0px 10px 0px 10px;">
<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
<tr>
<td bgcolor="#ffffff" align="left" style="padding: 20px 30px 40px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
<p style="margin: 0;">Cieszymy się że dołączyłeś do naszej społeczności Spotted Miasteczka Studenckiego! Potwierdź swoje konto klikając w poniższy przycisk:</p>
</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="left">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td bgcolor="#ffffff" align="center" style="padding: 20px 30px 60px 30px;">
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" style="border-radius: 3px;" bgcolor="#FFA73B"><a href={{ link }} target="_blank" style="font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid #FFA73B; display: inline-block;">Potwierdź konto</a></td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr> <!-- COPY -->

<tr>
<td bgcolor="#ffffff" align="left" style="padding: 0px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
<p style="margin: 0;">Jeśli masz jakieś pytania odwiedź zakładkę pomoc na naszej stronie.</p>
</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="left" style="padding: 0px 30px 40px 30px; border-radius: 0px 0px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
<p style="margin: 0;">Z pozdrowieniami <br>AGH MS SPOTTED Team</p>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td bgcolor="#f4f4f4" align="center" style="padding: 30px 10px 0px 10px;">
<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
<tr>
<td bgcolor="#FFECD1" align="center" style="padding: 30px 30px 30px 30px; border-radius: 4px 4px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
<h2 style="font-size: 20px; font-weight: 400; color: #111111; margin: 0;">Szukasz pomocy? </h2>
<p style="margin: 0;"><a href="https://msspotted.pl/contact/" target="_blank" style="color: #FFA73B;">Pomoc AGH MS SPOTTED</a></p>
</td>
 </tr>
</table>
</td>
</tr>
<tr>
<td bgcolor="#f4f4f4" align="center" style="padding: 0px 10px 0px 10px;">
<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
<tr>
<td bgcolor="#f4f4f4" align="left" style="padding: 0px 30px 30px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 18px;"> <br>
</td>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>