ms_web/members/urls.py
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path('',views.register,name='register'),
    path('logout/',views.logoutUser,name='logout'),
    path('profile/<int:pk>',views.profile, name='profile'),
    path('profile/edit_profile',views.edit_profile,name='edit_profile'),
    path('profile/edit_profile/password_change',views.password_change,name='password_change')
]

ms_web/ms_web/urls.py
from django.contrib import admin
#from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls
from django.views.static import serve

urlpatterns = [
                  path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
                  path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
                  path('admin/', admin.site.urls),
                  path('', include('msagh_website.urls')),
                  path('members/', include('members.urls')),
                  path('', include("django.contrib.auth.urls")),
                  path('email/', include(email_urls)),  # verification user path
              # 	path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
#path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
              ]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # Operation for images in meme section


handler404 = 'ms_web.views.handle_not_found'

ms_web/members/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.core.validators import RegexValidator


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Delete profile when user is deleted
    name = models.CharField(max_length=40, blank=True, default="Brak informacji")
    surname = models.CharField(max_length=40, blank=True, default="Brak informacji")

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Numer telefonu musi być zapisany we formacie: +123456789 ")
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    github_regex = RegexValidator(regex='^(http(s?):\/\/)?(www\.)?github\.([a-z])+\/([A-Za-z0-9]{1,})+\/?$',
                                  message="Podaj link do githuba!")
    github_url = models.CharField(validators=[github_regex], max_length=200, blank=True)
    contact_url = models.CharField(max_length=200, blank=True, default='Brak informacji')

    bio = models.TextField(max_length=500, blank=True, default="Brak informacji")
    country = CountryField(blank_label='Brak informacji', default='Brak informacji')

    def __str__(self):
        return f'{self.user.username} Profile'  # show how we want it to be displayed

ms_web/members/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from captcha.widgets import ReCaptchaV2Invisible 


from .models import Profile
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from django_countries import countries

class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Nazwa użytkownika',
        max_length=64,
        widget=forms.TextInput(attrs={'style': 'max-width: 18em'}),
        error_messages={'unique': "Konto z podaną nazwą użytkownika już istnieje!."}
    )
    email = forms.EmailField(
        max_length=64,
        widget=forms.TextInput(attrs={'style': 'max-width: 18em'}),
        error_messages={'Email already exists': "Konto z podanym adresem email już istnieje."}
    )
    password1 = forms.CharField(label="Hasło",
                                widget=forms.PasswordInput(attrs={'style': 'max-width: 18em'}),
                                error_messages={
                                    'password_mismatch': "The two password fields didn't match.",
                                },
                                help_text="Hasło musi zawierać co najmniej 8 znaków",

                                )
    password2 = forms.CharField(label="Powtórz hasło",
                                widget=forms.PasswordInput(attrs={'style': 'max-width: 18em'}),
                                error_messages={
                                    'password_mismatch': "The two password fields didn't match.",
                                }

                                )

    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox(api_params={'hl': 'cl', 'onload': 'onLoadFunc'}), label='',
                             error_messages={'required': ("Powyższe pole jest wymagane")})  # Rechaptcha

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError("Konto z podanym adresem email już istnieje.")
        return email

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class UpdateProfileForm(forms.ModelForm):
    country = CountryField(blank_label='Wybierz kraj',blank=True).formfield()
    class Meta:
        model = Profile
        fields = ['name','surname','phone','bio','github_url','contact_url','country']

        labels = {
            'name': 'Imię',
            'surname': 'Nazwisko',
            'phone': 'Numer telefonu',
            'bio': 'Biogram',
            'github_url': 'Github',
            'contact_url': 'Kontakt',
            'country':'Kraj pochodzenia'
        }

        # widgets = {
        #     'country': CountrySelectWidget(attrs={'class': 'form-select'}),
        # }

ms_web/members/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm, UpdateProfileForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth import get_user_model
from django_email_verification import send_email

from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import PasswordChangeForm
from datetime import timedelta
from ratelimit.decorators import ratelimit
from blacklist.ratelimit import blacklist_ratelimited
from .models import Profile
from msagh_website.models import Spot, CommentSpot
from .utils import compute_user_points
from django.contrib.auth.models import User
from django.contrib import messages  # import messages
#To not loged out after passwrod change
from django.contrib.auth import update_session_auth_hash

# Create your views here.

# if user or ip tried to send more 20 register request block him/it for 3 hour
@ratelimit(key='user_or_ip', rate='2000/h', block=False)
@blacklist_ratelimited(timedelta(minutes=180))
@csrf_exempt
def register(response):
    # Prevent loged in user to go on register page
    if response.user.is_authenticated:
        return redirect(reverse('msagh_website:base'))
    else:
        if response.method == "POST":
            form = RegisterForm(response.POST)
            if form.is_valid():
                user = form.save(commit=False)  # no save in database yet
                user_in_database = get_user_model().objects.create(username=user.username, password=user.password,
                                                                   email=user.email)
                user_in_database.is_active = False  # default set false
                send_email(user_in_database)  # send email with link to confirmation account

                return render(response, 'registration/success_register.html')
        else:
            form = RegisterForm()

        return render(response, 'members/register.html', {"form": form})


def logoutUser(request):
    logout(request)
    return render(request, 'members/logout.html')


@login_required(login_url='/login')
def profile(request, pk):
    user_profile = User.objects.get(pk=pk)

    no_comments = len(CommentSpot.objects.all().filter(user=user_profile))
    no_spots = len(Spot.objects.all().filter(user=user_profile, admin_aproved=True))
    points = compute_user_points(no_comments, no_spots, user_profile.date_joined)

    context = {
        'user_profile': user_profile,
        'points': points,
        'no_comments': no_comments,
        'no_spots': no_spots,

    }

    return render(request, 'members/profile.html', context)


# View to edit profile
@login_required(login_url='/login')
def edit_profile(request):
    if request.method == 'POST':
        # Getting form
        profile_form = UpdateProfileForm(request.POST, instance=request.user.profile)

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Twój profil został zaaktualizowany!')
            return redirect(reverse('members:profile', args=(request.user.pk,)))


    else:
        profile_form = UpdateProfileForm(instance=request.user.profile)
        #Changing label of country field - default it was 'country'
        profile_form['country'].label = 'Kraj pochodzenia'

    context = {
        'profile_form': profile_form,
        'user': request.user,
    }
    return render(request, 'members/edit_profile.html', context)


@login_required(login_url='/login')
def password_change(request):

    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            #TO not logged out after password change
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Twoje hasło zostało zaaktualizowane!')
            return redirect(reverse('members:profile', args=(request.user.pk,)))

    else:
        form = PasswordChangeForm(user=request.user)

    context = {
        'form':form
    }

    return render(request, 'members/password_change.html', context)

ms_web/members/templates/members/edit_profile.html
{% extends "base.html" %}

{% block content %}
<style>
{#Not display * next to form label#}
.asteriskField {
    display: none;
}



.form-content{
  width: 237%;
    position: center;
}

</style>

{% load crispy_forms_tags %}
    <br>
<h1 class="mb-3" align="center">Edycja profilu użytkownika</h1>
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
<br>
                <span class="font-weight-bold">{{ user.username }}</span>
                <br>
                <a> Data dołączenia: </a>
                <span class="text-black-50">{{ user.date_joined }}</span><span> </span>
                <br>
                <a> Ostatnie logowanie: </a>
                <span class="text-black-50">{{ user.last_login }}</span></div>
        </div>
        <div class="col-md-5 border-right">

    <div class="form-content">
        <form method="post" enctype="multipart/form-data">
                {% csrf_token %}



            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                            <br>
                        <br>
                            {{ profile_form.name|as_crispy_field }}
                        <br>


                            {{ profile_form.surname|as_crispy_field }}
                    </div>
                    <br>
                    <div class="form-group">
                        <a href="{%url 'members:password_change' %}" class="btn btn-dark" role="button">Zmień hasło</a>


                        <hr>
                {{ profile_form.phone|as_crispy_field  }}
                        <br>
                 {{ profile_form.bio|as_crispy_field }}
                        <br>
                 {{ profile_form.github_url|as_crispy_field }}
                        <br>

                 {{ profile_form.contact_url|as_crispy_field }}
                        <br>






                    {{ profile_form.country|as_crispy_field }}
                </div>
            <br>
            <button type="submit" class="btn btn-dark btn-lg">Zapisz zmiany</button>
            <button type="reset" class="btn btn-dark btn-lg">Reset</button>
            </div>
            <br>
        </form>
    </div>

{% endblock content %}

ms_web/members/templates/members/logout.html
{% extends "base.html"%}

{%block content%}
     <h3>

 </h3>
<div class="container">
 <h1>

 </h1>
     <h2>

 </h2>

     <h3>

 </h3>
  <div class="text-center">
    <h1>Zostałeś poprawnie wylogowany </h1>
    <p class="lead">Dziękujemy za wizyte na naszej stronie!</p>
  </div>

</div><!-- /.container -->

<!-- Small modal -->
<div class="modal" id="logoutModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4>Log Out <i class="fa fa-lock"></i></h4>
      </div>
      <div class="modal-body">
        <p><i class="fa fa-question-circle"></i> Are you sure you want to log-off? <br /></p>
        <div class="actionsBtns">
            <form action="/logout" method="post">
                <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
                <input type="submit" class="btn btn-default btn-primary" data-dismiss="modal" value="Logout" />
	                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock content%}

ms_web/members/templates/members/password_change.html
{% extends "base.html" %}

{% block content %}
 <style>
  button{
            margin-top: 20px;
            align-content: center;
            outline: none !important;

        }

  #id_new_password1{
          width: 40%;
          margin-top: 5px;
            margin-bottom: 15px;
      }

  #id_new_password2{
          width: 40%;
          margin-top: 5px;

      }

  #id_old_password{
      width: 40%;
      margin-bottom: 15px;
          margin-top: 5px;
  }
 </style>


  {% load crispy_forms_tags %}

  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Zmiana hasła</h2>
		<hr>
        <p>Podaj swoje nowe hasło</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Zmień hasło</button>
        </form>
    </div>

{% endblock %}

ms_web/members/templates/members/profile.html
{% extends "base.html"%}
{%block content%}
{#    TODO: MAKE LABEL RESIZABLE TO AVOID CRASH PAGE LIKE BARTOSZ TABISZ#}

{% load static %}

<style>
    <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">


.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
</style>

<h1 style="margin-top: 8px" class="mb-3" align="center"> Profil użytkownika</h1>
<div class="container">
    <div class="main-body">

          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">  </a></li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                        {% if user_profile.is_superuser %}
                      <h4><span style='font-size:20px;'>&#9733;</span>{{ user_profile.username }}</h4>
                        {% else %}
                        <h4>{{ user_profile.username }}</h4>
                        {% endif %}

                        <p class="text-secondary mb-1">{{ user_profile.profile.bio }}</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg> Data dołączenia:</h6>
                    <span class="text-secondary">{{ user_profile.date_joined }}</span>
                  </li>
           <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg> Ostatnie logowanie:</h6>
                    <span class="text-secondary">{{ user_profile.last_login }}</span>
                  </li>

{#                            In order to wrap text#}
                  <li style="word-wrap:break-word; list-style: none; margin-left: 15px; margin-top: 8px; margin-right: 3px;margin-bottom: -10px ">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg> Github</h6>
                    <span class="text-secondary">{{ user_profile.profile.github_url }}</span>
                  </li>
                    <hr style="height:1px; color: rgba(75,85,87,0.73);">

                    {#                            In order to wrap text#}
                  <li style="word-wrap:break-word; list-style: none; margin-left: 15px; margin-top: -8px; margin-right: 3px;margin-bottom: 10px ">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg> Kontakt </h6>
                    <span class="text-secondary">{{ user_profile.profile.contact_url }}</span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-5" style="margin-bottom: 6px;">
                      <h6 class="mb-0">Punkty Użytkownika </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ points }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-5" style="margin-bottom: 6px;">
                      <h6 class="mb-0">Posty użytkownika </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ no_spots }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-5" style="margin-bottom: 6px;">
                      <h6 class="mb-0">Odpowiedzi użytkownika </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ no_comments }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-5" style="margin-bottom: 6px;">
                      <h6 class="mb-0">Imię</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user_profile.profile.name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-5" style="margin-bottom: 6px;">
                      <h6 class="mb-0">Nazwisko</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user_profile.profile.surname }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-5" style="margin-bottom: 6px;">
                      <h6 class="mb-0">Kraj pochodzenia</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">


                    {{ user_profile.profile.country.name }}
{#                        path to flag#}
                    <img alt="" src="{{ request.scheme }}://{{ request.get_host }}{{ user_profile.profile.country.flag}}">



                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-5" style="margin-bottom: 6px;">
                      <h6 class="mb-0">Telefon</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user_profile.profile.phone }}
                    </div>
                  </div>
                  <hr>
                </div>
              </div>

<!--              <div class="row gutters-sm center ">-->
<!--                <div class="col-sm-6 mb-3 center">-->
<!--                  <div class="card h-100 center ">-->
<!--                    <div class="card-body">-->
<!--                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>Statystyki Użytkownika</h6>-->
<!--                      <small>Napisane posty: </small>-->
<!--                      <div class="progress mb-3" style="height: 5px">-->
<!--                        <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>-->
<!--                      </div>-->
<!--                      <small>Napisane komentarze </small>-->
<!--                      <div class="progress mb-3" style="height: 5px">-->
<!--                        <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>-->
<!--                      </div>-->
<!--                      <small>One Page</small>-->
<!--                      <div class="progress mb-3" style="height: 5px">-->
<!--                        <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->



            </div>
          </div>

        </div>
    </div>
{%endblock content%}

ms_web/members/templates/members/register.html
{% extends "base.html"%}

{%block content%}
<style>
.text-center {                             {#Centering captcha field#}
        text-align: center;
    }

    .g-recaptcha {
        display: inline-block;
        margin-top: 12px;
    }


.asteriskField {
    display: none;                      {#Deleting * from label#}
}

.form-group {
margin: auto;
width: 60%;
    text-align: center;
    user-input: center;

padding: 8px;
}
#id_username{
               display: table;
    margin: 0 auto;
    border: 1px solid black;
}


#id_email{
           display: table;
    margin: 0 auto;
    border: 1px solid black;
}
#id_password1{
       display: table;
    margin: 0 auto;
    border: 1px solid black;
}
#id_password2{
       display: table;
    margin: 0 auto;
    border: 1px solid black;
}

#id_g-recaptcha-response{

align-content: center;
    align-self: center;
}



.form-text text-muted{
    color: white;
    background-color: white;
}
button{
    /*Change the width as much as you like, but make sure
    margin-left and margin-right + width = 100%*/
       display: table;
    margin: 0 auto;
    border: 1px solid black;
}

</style>

<body>
{% load crispy_forms_tags %}
<form method="post" class = 'form-group'>
     {% csrf_token %}
{#    {{form.username|as_crispy_field}}#}
{##}
{#    {{form.email|as_crispy_field}}#}
{##}
{#    {{form.password1|as_crispy_field}}#}
{##}
{#    {{form.password2|as_crispy_field}}#}
    {{ form|crispy }}
<div align="center" style="margin-bottom: 12px; margin-top: 16px">
{#    {{form.captcha}}#}
</div>

    <button type="submit" class="btn btn-primary btn-lg">Zarejestruj się</button>
</form>
</body>
</html>
{%endblock content%}